### ISSUE TITLE
NPE when start-up followed by unclean shutdown

### ISSUE THREAD

**Issue by bmistry13** [walmartlabs/mupd8#58] opened 2015-02-19 20:26 UTC
In addition to that,  Mupd8 library does throw NP, due to duplicated raws in DB/or previous unclean shutdown (issue with mupd8 code).

10 Feb 2015 19:16:06,627 ERROR [MessageServer] (grizzled.slf4j.Logger.error:116)  - MessageServerThread exception.
java.lang.NullPointerException
        at com.walmartlabs.mupd8.MessageServer$$anonfun$run$10.apply(MessageServer.scala:132)
        at com.walmartlabs.mupd8.MessageServer$$anonfun$run$10.apply(MessageServer.scala:128)
        at scala.collection.immutable.Map$Map4.foreach(Map.scala:181)
        at com.walmartlabs.mupd8.MessageServer.run(MessageServer.scala:128)
10 Feb 2015 19:16:06,688 ERROR [MessageServer] (grizzled.slf4j.Logger.error:116)  - MessageServerThread exception.
java.lang.NullPointerException
        at com.walmartlabs.mupd8.MessageServer$$anonfun$run$10.apply(MessageServer.scala:132)
        at com.walmartlabs.mupd8.MessageServer$$anonfun$run$10.apply(MessageServer.scala:128)
        at scala.collection.immutable.Map$Map4.foreach(Map.scala:181)
        at com.walmartlabs.mupd8.MessageServer.run(MessageServer.scala:128)

Thanks,
Bhavesh

**Comment by YiqianZ** [comment] 2015-03-03 17:35
Based on the discussion with Mayur, I tried the two scenarios which possibly caused issue#58. 

The first one is to shut down the mupd8 on some of the multiple hosts in the hash ring, Mupd8 on the rest hosts works properly.  Then shut down all of them, and then restart the Mupd8 on some of the multiple hosts,  Mupd8 works properly.

The second one is to start two Mupd8  in same Cassandra with same keyspace and same column family, each Mupd8 has its own message server, then shut down them, and then restart one Mupd8.    My observation is that  we will have two records for the two mupd8 in Cassandra firstly, the records remains there after shutting down the two Mupd8 , then restart one Mupd8 and the value of related record will be updated.   Mupd8 works properly, instead of throw NullPointerException. 

So, I cannot reproduce the issue #58 currently.  

Mayur also tried some experiments and could not reproduce the issue. 

So, I decide to close the issue. 

If the issue appears later, please give more detailed information about how to reproduce it.

**Closed** 2015-03-03 17:35 UTC

**Comment by bmistry13** [comment] 2015-03-03 19:11
Can we at least fix the NPE ?

Thanks,
Bhavesh

**Comment by YiqianZ** [comment] 2015-03-03 19:28
Currently, NPE cannot be reproduced.
